### ISSUE TITLE
Missing output requirement in documentation

### ISSUE THREAD

**Issue by marcransome** [marcransome/remove-ansi-colors#6]
There is no mention of a required step output in the current documentation. For example, the `colored` output in:

```yaml
- name: Generate string with ANSI color codes
id: generate-colored-output
run: |
  colored=$(printf '\e[0;31mRED\e[0m')
  echo "::set-output name=colored::$colored"
```

An example such as this should be added to avoid ambiguity.
